In [1]:
def analyze_graham_value(ticker,price,eps,book_value):

  if eps <= 0 or book_value <= 0:
    return f"{ticker}: fails criteria"

  graham_number = (22.5 * eps * book_value) ** .5
  if price < graham_number:
    discount = ((graham_number-price) / graham_number) * 100
    return f"{ticker}: underpriced"
  else:
      premium =((price-graham_number) / graham_number) * 100
      return f"{ticker}: overpriced"

portfolio_sandbox = [{"ticker": "comp a", "price": 45.00, "eps": 3.50, "book_value": 22.00 },{"ticker": "comp b", "price": 120.00, "eps": 2.10, "book_value": 15.50}, {"ticker": "comp c","price": 15, "eps": -.5, "book_value": 8.00}]

print("running graham filter")
for stock in portfolio_sandbox:
    result = analyze_graham_value(
            stock["ticker"],
            stock["price"],
            stock["eps"],
            stock["book_value"])
print(result)

running graham filter
comp c: fails criteria

In [ ]:
import pandas as pd
raw_data = {
    "ticker":["comp a","comp b","comp c"],
    "price" :[45.00,120.00,15.00],
    "eps" : [3.5, 2.1, -.5],
    "book_value" : [22,15.5,8]

}
df = pd.DataFrame(raw_data)
print("first dataframe")
display(pd)

df["pe_ratio"] = df["price"] / df["eps"]
print("table with pe ratio")
display(df)

first dataframe

table with pe ratio

   ticker  price  eps  book_value   pe_ratio
0  comp a   45.0  3.5        22.0  12.857143
1  comp b  120.0  2.1        15.5  57.142857
2  comp c   15.0 -0.5         8.0 -30.000000

In [ ]:
!pip install yfinance

Requirement already satisfied: yfinance in /usr/local/lib/python3.12/dist-packages (0.2.66)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.0.2)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.32.4)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.0.13)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.10.0)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.4.7)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.2.2)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.13.5)
Requirement already satisfied: curl_cffi>=0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.15.0)
Requirement already satisfied: protobuf>=3.19.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (5.29.6)
Requirement already satisfied: websockets>=13.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (15.0.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8.4)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (4.16.0)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2.1.0)
Requirement already satisfied: certifi>=2024.2.2 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2026.6.17)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (13.9.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2026.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (2.5.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0.0->curl_cffi>=0.7->yfinance) (3.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->curl_cffi>=0.7->yfinance) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->curl_cffi>=0.7->yfinance) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.7->yfinance) (0.1.2)

In [ ]:
import yfinance as yf
import pandas as pd

ticker = "AAPL"
data = yf.download(ticker, start="2026-04-01", end="2026-07-01")

print("historical data for {ticker}")
display(data.head())

/tmp/ipykernel_1030/1433907588.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker, start="2026-04-01", end="2026-07-01")
[*********************100%***********************]  1 of 1 completed

historical data for {ticker}

Price            Close        High         Low        Open    Volume
Ticker            AAPL        AAPL        AAPL        AAPL      AAPL
Date
2026-04-01  255.394699  255.944181  253.096813  253.846123  40059400
2026-04-02  255.684433  255.894246  250.419280  253.966015  31289400
2026-04-06  258.621704  261.918685  256.223919  256.273892  29329900
2026-04-07  253.266663  255.964190  245.473839  255.924218  62148000
2026-04-08  258.661682  259.510906  256.293869  258.212115  41032800

In [ ]:
data['SMA_20'] = data['Close'].rolling(window=20).mean()
print("data with 20 day moving average")
display(data.tail(10))

data with 20 day moving average

Price,Close,High,Low,Open,Volume,SMA_20
Ticker,AAPL,AAPL,AAPL,AAPL,AAPL,
Date,,,,,,
2026-06-16,299.239990,300.480011,293.970001,295.250000,39874400,303.760501
2026-06-17,295.950012,302.070007,294.359985,300.850006,42745100,303.609502
2026-06-18,298.010010,300.570007,295.619995,298.109985,85962200,303.397502
2026-06-22,297.010010,302.420013,296.760010,297.309998,44879900,302.998503
2026-06-23,294.299988,301.640015,294.179993,297.540009,52010900,302.272502
2026-06-24,293.079987,299.700012,292.940002,295.359985,53081900,301.510002
2026-06-25,275.149994,288.799988,273.750000,287.399994,107013700,299.725002
2026-06-26,283.779999,285.950012,274.209991,275.000000,261775500,298.288501
2026-06-29,281.739990,288.369995,279.850006,286.730011,66427000,296.772501
2026-06-30,289.359985,289.940002,280.700012,281.170013,65100200,295.925000